#!/bin/bash

parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
cd "$parent_path"

sources=(*.cpp)
tests="${sources[@]/.cpp/.tst}"

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

if [[ $# -eq 1 ]]; then
	if [[ -f "$1.cpp" ]]; then
		test="$1.tst"
	elif [[ -f $1 ]]; then
		test=$1
	else
		echo Test $1 does not exist
		exit 1
	fi

	make $test

	./$test
	if [[ $? -eq 0 ]]; then 	# success
		echo -e "${GREEN}Passed ${test}${NC}"
		exit 0
	else 						# failure
		echo -e "\n${RED}Failed Test ${test}${NC}"
		exit 1
	fi
fi

# make temp file
tmpfile=$(mktemp /tmp/abc-script.XXXXXX)
exec 3>"$tmpfile"
exec 4<"$tmpfile"
rm "$tmpfile"

for test in $tests; do
	make $test
	./$test >&3
	if [[ $? -eq 0 ]]; then 	# success
		echo -e "${GREEN}Passed ${test}${NC}"
	else 						# failure
		cat <&4
		echo -e "\n${RED}Failed Test ${test}${NC}"
		exit 1
	fi
done