#!/bin/bash

parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
cd "$parent_path"

TESTS=*.tst

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

if [[ $# -eq 1 ]]; then
	if [[ -f "$1.tst" ]]; then
		TEST="$1.tst"
	elif [[ -f $1 ]]; then
		TEST=$1
	else
		echo Test $1 does not exist
		exit 1
	fi

	./$TEST
	if [[ $? -eq 0 ]]; then 	# success
		echo -e "${GREEN}Passed ${TEST}${NC}"
		exit 0
	else 						# failure
		echo -e "\n${RED}Failed Test ${TEST}${NC}"
		exit 1
	fi
fi

for TEST in $TESTS; do
	./$TEST >& /dev/null
	if [[ $? -eq 0 ]]; then 	# success
		echo -e "${GREEN}Passed ${TEST}${NC}"
	else 						# failure
		echo
		./$TEST
		echo -e "\n${RED}Failed Test ${TEST}${NC}"
		break
	fi
done